pipeline:

  build-airflow-operator:
    image: astronomerio/operator-sdk:v0.5.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - make build-airflow-operator
    environment:
      - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
      - ASTRONOMER_AIRFLOW_OPERATOR_VERSION=${DRONE_TAG##v}
#    when:
#      event: tag
#      branch: [ master, release-* ]

  push-airflow-operator:
    group: push
    image: astronomerio/operator-sdk:v0.5.0
    commands:
      - docker login -u $${DOCKER_USERNAME} -p $${DOCKER_PASSWORD}
      - make push-airflow-operator
    environment:
      - ASTRONOMER_AIRFLOW_OPERATOR_VERSION=0.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [ docker_username, docker_password ]

  notify:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: airflow-operator
    when:
      status: [ success ]
